"""
UI package for the Muesli application.

This package contains the user interface components for the application,
including the main window and QML files.
"""

from ui.main_window import MainWindow

# Import compiled Qt resources (resources_rc) if available.
# This module is generated by `pyside6-rcc` (see ui/compile_resources.py).
# The try/except ensures the UI still works even if the resources haven’t
# been compiled yet (e.g. during initial setup or in headless CLI mode).
try:
    from . import resources_rc  # noqa: F401  (import side-effect registers resources)
except ModuleNotFoundError:  # pragma: no cover
    # Resources haven’t been compiled; icons/animations may be missing but the
    # application can continue to function. Developers can run:
    #   python ui/compile_resources.py
    # to generate the module.
    pass

__all__ = ["MainWindow"]
